### ISSUE TITLE
Endless number of styles created

### ISSUE THREAD

**Issue by donaldpipowitch** [rofrischmann/react-fela#11]
Hi, I try to use fela with mobx. I don't know why, but in this example a certain style is recreated endlessly: http://www.webpackbin.com/4y018rLjZ

```
import React, { PropTypes, Component } from 'react';
import { observable, autorun } from 'mobx';
import { observer } from 'mobx-react';
//import { connect } from 'react-fela';

// state
const state = observable({
  seconds: 0
});
setInterval(() => state.seconds += 1, 1000);

// style
const rendererShape = PropTypes.shape({
  renderFont: PropTypes.func.isRequired,
  renderStatic: PropTypes.func.isRequired,
  renderRule: PropTypes.func.isRequired,
  renderKeyframe: PropTypes.func.isRequired
}).isRequired;

const title = props => ({
  color: props.seconds % 2 === 0 ? 'blue' : 'red'
});

// component
const HelloWorld = observer((_, context) => {
  const titleClassName = context.renderer.renderRule(title, state);
  return <h1 className={titleClassName}>Seconds elapsed: {state.seconds}</h1>;
});

HelloWorld.contextTypes = {
  renderer: rendererShape
};

export default HelloWorld;
```

I know I call `color: props.seconds % 2 === 0 ? 'blue' : 'red'` on every second, but I thought that either
1. Cache should work, so only two styles are created
2. everything should be re-created, but only the _blue_ case is recreated
3. the old styles should be removed, if they are no longer in use

For the _red_ state my component always gets the class `c0` while the _blue_ state gets `c0 c0-{XXXX}`. Is this normal?

**Comment by rofrischmann** [comment]
Basically the renderer re-creates every class, because the `props` **always** change (as you pass the state directly) and the className gets created with a hash of the props.

Yet there should be both classes for blue and red... I will have to test this somehow to get the problem. Btw. it would be better to do sth. like:

```javascript
const title = props => ({
  color: props.isEven ? 'blue' : 'red'
})

const titleClassName = context.renderer.renderRule(title, {
  isEven: state.seconds % 2
})
```

**Comment by donaldpipowitch** [comment]
Thank you for the explanation, but why should I use `isEven` instead of the calculation? Where is the difference?

**Comment by rofrischmann** [comment]
Well because you're save to say you pass a flat bool prop which is either `true` or `false`. So basically there are only 2 different prop values which means the renderer renders a maximum of 2 classes. Passing the state directly causes different props value every time and results in several CSS classes with the same rules (because `{ seconds: 4 }` and `{ seconds: 2 }` result in different hashes although the rendered color is the same)

Also in general calculation and evaluation should be done outside of the rule to keep it simple, declarative and less error-prone.

**Comment by donaldpipowitch** [comment]
So the hash depends on the passed props, not the generated CSS?

**Comment by rofrischmann** [comment]
Yap. We need to do this because we diff styles and only take the dynamic amount by props. But I will add another layer of cache to the renderer.
